### ISSUE TITLE
AethysCore decrepated

### ISSUE THREAD

**Issue by NLZ** [SimCMinMax/MoreTooltipInfo#2]
So I was looking for any way to disable the duplicated IDs (using idTip already), and I found my way to this line:
https://github.com/SimCMinMax/MoreItemInfo/blob/cf66ff7ce7a255695f09fed3f1bc775912c7cdfc/UI.lua#L2

I dont think you need me to explain this but this is all sort of wrong, with the library renamed to HeroLib, not checking if the library is present, not refering to it in the toc and not including it in the package. 
Although this HeroLib looks quite heavyweight for such a simple addon.

So may I ask someone to restore the options?

**Comment by Kutikuti** [comment]
Hey, sorry for the late reply, 
the UI.lua file was not meant to be pushed to the repo at this stage because I was working on the UI (before the herolib change). That's why it's not in the TOC file, and so has no impact on the addon at all other than taking 3ko of disk space
